export const USER_MESSAGES = {
  CREATE_SUCCESS: 'User created successfully',
  CREATE_ERROR: 'Error creating user',
  UPDATE_SUCCESS: 'User updated successfully',
  UPDATE_ERROR: 'Error updating user',
  DELETE_SUCCESS: 'User deleted successfully',
  DELETE_ERROR: 'Error deleting user',
  NOT_FOUND: 'User not found',
  INVALID_CREDENTIALS: 'Invalid username or password',
  NOT_EXIST: 'User does not exist',
  ALREADY_EXIST: 'User already exists',
  FETCH_SUCCESS: 'Users fetched successfully',
  FETCH_ERROR: 'Error fetching users',
  USERNAME_EXISTS: 'Username already exists',
  EMAIL_EXISTS: 'Email already exists',
  PHONE_NUMBER_EXISTS: 'Phone number already exists',
  LOGIN_SUCCESS: 'Login successful',
  USER_NOT_FOUND: 'User not found',
};
